services:
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    # depends_on:
    #   - redis
    #   - minio
    #   - oauth

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"

  # redis:
  #   image: redis:7.4.2-alpine-3.21
  #   ports:
  #     - "6379:6379"

  # minio:
  #   image:
